version: "3.9"
services:
  runner:
    build: 
      context: .
      dockerfile: ./aatp/infra/runner/Dockerfile
    volumes:
      - ./aatp/http_webrtc:/runner
      - ./aatp/result:/result
      - webexec_auth:/webexec_config
    environment:
      PWARGS: ${PWARGS}
    depends_on:
      - terminal7
      - webexec
  terminal7:
    image: halverneus/static-file-server:latest
    environment:
      PORT: 80
    volumes:
      - ./dist:/web
  webexec:
    build:
      context: .
      dockerfile: ./aatp/webexec/Dockerfile
    volumes:
      - ./aatp/http_webrtc/webexec_conf:/conf
      - webexec_auth:/auth
volumes:
  webexec_auth:
