version: "3.9"
services:
  runner:
    build: 
      context: .
      dockerfile: ./aatp/infra/runner/Dockerfile
    volumes:
      - ./aatp/http_webrtc:/runner
      - ./aatp/common:/common
      - ./aatp/result:/result
      - webexec_auth:/webexec_config
    environment:
      PWARGS: ${PWARGS--x}
    depends_on:
      - terminal7
      - webexec
  terminal7:
    image: halverneus/static-file-server:latest
    environment:
      PORT: 80
    volumes:
      - ./dist:/web
  webexec:
    build:
      context: .
      dockerfile: ./aatp/infra/webexec/Dockerfile
      args:
        REF: ${WEBEXEC_REF-master}
    environment:
      WEBEXEC_SERVER_URL: http://webexec:7777
    volumes:
      - ./aatp/http_webrtc/webexec_conf:/conf
      - webexec_auth:/auth
    stop_grace_period: 1s
    init: true
volumes:
  webexec_auth:
