version: "3.9"
services:
  runner:
    build: 
      context: .
      dockerfile: ./aatp/infra/runner/Dockerfile
    volumes:
      - ./aatp/peerbook_webrtc:/runner
      - ./aatp/common:/common
      - ./aatp/result:/result
    depends_on:
      - peerbook
      - webexec
      - terminal7
    environment:
      PWARGS: ${PWARGS--x -j 1}
  terminal7:
    image: halverneus/static-file-server:latest
    expose:
      - 80
    environment:
      PORT: 80
    volumes:
      - ./dist:/web
  webexec:
    build:
      context: .
      dockerfile: ./aatp/infra/webexec/Dockerfile
      args:
        REF: ${WEBEXEC_REF-master}
    environment:
      PEERBOOK: 1
      WEBEXEC_SERVER_URL: http://webexec:7777
    depends_on:
      - peerbook
    volumes:
      - ./aatp/peerbook_webrtc/webexec_conf:/conf
      - ./aatp/result:/result
    stop_grace_period: 1s
    init: true
  peerbook:
    build:
      context: .
      dockerfile: ./aatp/infra/peerbook/Dockerfile
      args:
        REF: ${PEERBOOK_REF-master}
    expose:
      - 17777
    depends_on:
      - redis
      - revenuecat
    environment:
      REDIS_HOST: redis:6379
      REVENUECAT_URL: http://revenuecat:1080
      PB_SMTP_HOST: smtp
      PB_SMTP_PORT: 1025
      PB_HOME_URL: http://peerbook:17777
      WEBEXEC_SERVER_URL: http://peerbook:17777
  redis:
    build:
      context: .
      dockerfile: ./aatp/infra/redis/Dockerfile
  revenuecat:
    image: "mockserver/mockserver"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/revenuecat_double.json
      MOCKSERVER_LOG_LEVEL: WARN
    expose:
      - 1080
    volumes:
      - ./aatp/peerbook_webrtc:/config
  smtp:
    image: jcalonso/mailhog
    expose:
      - 1025
      - 8025
