require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
platform :ios, '15.4'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorClipboard', :path => '../../node_modules/@capacitor/clipboard'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapgoCapacitorPurchases', :path => '../../node_modules/@capgo/capacitor-purchases'
  pod 'CapacitorNativeBiometric', :path => '../../node_modules/capacitor-native-biometric'
  pod 'CapacitorRateApp', :path => '../../node_modules/capacitor-rate-app'
  pod 'CapacitorSshPlugin', :path => '../../node_modules/capacitor-ssh-plugin'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
post_install do |installer|
  assertDeploymentTarget(installer)
end
